#!/bin/sh
# chkconfig:345 90 90
# description:tomcat
# This shell script enables the automatic use of tomcat
#

source /etc/profile
export CATALINA_BASE=/usr/local/tomcat
export CATALINA_HOME=/usr/local/tomcat
export LD_LIBRARY_PATH=/usr/local/tomcat/lib

RETVAL=0

start() {
  echo -n "Tomcat Starting..."
  echo
#  $CATALINA_HOME/bin/daemon.sh start
  $CATALINA_HOME/bin/catalina.sh start
}

stop() {
  echo -n "Tomcat Stop..."
  echo
#  $CATALINA_HOME/bin/daemon.sh stop
  $CATALINA_HOME/bin/catalina.sh stop
}

restart() {
  echo -n "Tomcat restart..."
  echo
  stop
  start
}

case "$1" in
  start)
    start;;
  stop)
    stop;;
  restart)
    restart;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $RETVAL
