#!/bin/sh
# chkconfig:345 90 90
# description:elasticsearch
# This shell script enables the automatic use of elasticsearch
#

source /etc/profile

PROGRAM=/usr/local/es/bin/elasticsearch
CONFFILE=/var/es/config/elasticsearch.yml
PIDFILE=/var/es/es.pid

RETVAL=0

start() {
  echo -n "Elasticsearch Starting..."
  echo
  su es -c "$PROGRAM -d --path.conf=`dirname $CONFFILE`"

  if [ ! -z "$PIDFILE" ]; then
    ps aux|grep `dirname $CONFFILE`|grep -v "grep"|awk '{print $2}' > "$PIDFILE"
  fi
}

stop() {
  echo -n "Elasticsearch Stop..."
  echo
  if [ ! -z "$PIDFILE" ]; then
    if [ -f "$PIDFILE" ]; then
      kill -9 `cat "$PIDFILE"` >/dev/null 2>&1
      rm -f "$PIDFILE" >/dev/null 2>&1
    fi
  fi
}

restart() {
  echo -n "Elasticsearch restart..."
  echo
  stop
  start
}

case "$1" in
  start)
    start;;
  stop)
    stop;;
  restart)
    restart;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $RETVAL
