#! /bin/sh
# chkconfig:345 60 60
# description:nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server

PRGFILE=/usr/local/nginx/sbin/nginx
CONFIGFILE=/usr/local/nginx/conf/nginx.conf
PIDFILE=/usr/local/nginx/logs/nginx.pid

set -e
[ -x "$PRGFILE" ] || exit 0

do_start() {
 $PRGFILE -c $CONFIGFILE || echo -n "nginx already running"
}

do_stop() {
 kill -INT `cat $PIDFILE` || echo -n "nginx not running"
}

case "$1" in
 start)
 echo -n "Starting nginx ..."
 do_start
 echo "."
 ;;
 stop)
 echo -n "Stopping nginx ..."
 do_stop
 echo "."
 ;;
 restart)
 echo -n "Restarting nginx ..."
 do_stop
 do_start
 echo "."
 ;;
 *)
 echo "Usage: $0 {start|stop|reload|restart}"
 exit 1
 ;;
esac

exit 0
